<?xml version="1.0"?>


<robot name="ares" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<material name="red">
		<color rgba="1 0 0 1"/>
	</material>

	<material name="black">
		<color rgba="0 0 0 1"/>
	</material>




	<link name="base_link"/>

	

	<xacro:property name="chassisWidth" value="0.203" />
	<xacro:property name="chassisHeight" value="0.093" />
	<xacro:property name="chassisLength" value="0.333" />
	<xacro:property name="wheelRadius" value="0.06" />
	<xacro:property name="wheelWidth" value="0.05" />


	<link name="chassis">
		<visual>
			<geometry>
				<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${chassisHeight/2}"/>
			<material name="red"/>
		</visual>
		<collision>
			<geometry>
				<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="5"/>
			<inertia ixx="0.046204" ixy="0.0" ixz="0.0"
               iyy="0.01717" iyz="0.0"
               izz="0.063374" />
		</inertial>
	</link>

	<gazebo reference="chassis">
    	<material>Gazebo/DarkGrey</material>
  	</gazebo>

	<joint name="base_joint" type="fixed">
    	<parent link="base_link"/>
    	<child link="chassis"/>
    	<origin xyz="0.0 0.0 0.044250" rpy="0 0 0"/>
  	</joint>


	<link name="left_rear_wheel_link">
		<visual>
			<geometry>
				<cylinder length="${wheelWidth}" radius="${wheelRadius}"/>	
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<material name="black"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${wheelWidth}" radius="${wheelRadius}"/>	
			</geometry>
		</collision>
		<inertial>
			<mass value="0.150"/>
			<inertia ixx="0.0002281" ixy="0.0" ixz="0.0"
               iyy="0.0002281" iyz="0.0"
               izz="0.00027" />
		</inertial>
	</link>

	<joint name="left_rear_wheel_joint" type="continuous">
		<parent link="chassis"/>
		<child link="left_rear_wheel_link"/>
		<axis xyz="0 0 1"/>
		<origin rpy="1.57075 0 0" xyz="-0.089 0.12862 0.01575"/>
	</joint>

	<transmission name="left_rear_wheel_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<actuator name="left_rear_wheel_motor">
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
		<joint name="left_rear_wheel_joint">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		</joint>
	</transmission>

	<gazebo reference="left_rear_wheel_link">
		<mu1 value="200.0"/>
		<mu2 value="100.0"/>

		<material>Gazebo/Grey</material>
	</gazebo>



	<link name="left_front_wheel_link">
		<visual>
			<geometry>
				<cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<material name="black"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${wheelWidth}" radius="${wheelRadius}"/>	
			</geometry>
		</collision>
		<inertial>
			<mass value="0.150"/>
			<inertia ixx="0.0002281" ixy="0.0" ixz="0.0"
               iyy="0.0002281" iyz="0.0"
               izz="0.00027" />
		</inertial>
	</link>

	<joint name="left_front_wheel_joint" type="continuous">
		<parent link="chassis"/>
		<child link="left_front_wheel_link"/>
		<axis xyz="0 0 1"/>
		<origin rpy="1.57075 0 0" xyz="0.089 0.12862 0.01575"/>
	</joint>

	<transmission name="left_front_wheel_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<actuator name="left_front_wheel_motor">
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
		<joint name="left_front_wheel_joint">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		</joint>
	</transmission>

	<gazebo reference0="left_front_wheel_link">
		<mu1 value="0.01"/>
		<mu2 value="0.01"/>

		<material>Gazebo/Grey</material>
	</gazebo>



	<link name="right_rear_wheel_link">
		<visual>
			<geometry>
				<cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
			</geometry>
			<origin rpy="1.57075 0 0" xyz="0 0 0"/>
			<material name="black"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${wheelWidth}" radius="${wheelRadius}"/>	
			</geometry>
		</collision>
		<inertial>
			<mass value="0.150"/>
			<inertia ixx="0.0002281" ixy="0.0" ixz="0.0"
               iyy="0.0002281" iyz="0.0"
               izz="0.00027" />
		</inertial>
	</link>

	<joint name="right_rear_wheel_joint" type="continuous">
		<parent link="chassis"/>
		<child link="right_rear_wheel_link"/>
		<axis xyz="0 0 1"/>
		<origin rpy="0 0 0" xyz="-0.089 -0.12862 0.01575"/>
	</joint>

	<transmission name="right_rear_wheel_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<actuator name="right_rear_wheel_motor">
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
		<joint name="right_rear_wheel_joint">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		</joint>
	</transmission>

	<gazebo reference="right_rear_wheel_link">
		<mu1>0.1</mu1>
    <mu2>0.1</mu2>
    <kp>500000.0</kp>
    <kd>10.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>0.1</maxVel>
    <fdir1>1 0 0</fdir1>
		<material>Gazebo/Grey</material>
	</gazebo>



	<link name="right_front_wheel_link">
		<visual>
			<geometry>
				<cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
			</geometry>
			<origin rpy="1.57075 0 0" xyz="0 0 0"/>
			<material name="black"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${wheelWidth}" radius="${wheelRadius}"/>	
			</geometry>
		</collision>
		<inertial>
			<mass value="0.150"/>
			<inertia ixx="0.0002281" ixy="0.0" ixz="0.0"
               iyy="0.0002281" iyz="0.0"
               izz="0.00027" />
		</inertial>
	</link>

	<joint name="right_front_wheel_joint" type="continuous">
		<parent link="chassis"/>
		<child link="right_front_wheel_link"/>
		<axis xyz="0 0 1"/>
		<origin rpy="0 0 0" xyz="0.089 -0.12862 0.01575"/>
		<dynamics friction="10"/>
	</joint>

	<transmission name="right_front_wheel_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<actuator name="right_front_wheel_motor">
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
		<joint name="right_front_wheel_joint">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		</joint>
	</transmission>

	<gazebo reference="right_front_wheel_link">
		<mu1>10</mu1>
    <mu2>10</mu2>
    <kp>500000.0</kp>
    <kd>10.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>0.1</maxVel>
    <fdir1>1 0 0</fdir1>
		<material>Gazebo/Grey</material>
	</gazebo>

<!-- 	<link name="front_handle">
		<visual>
			<geometry>
				<box size="0.03 0.280 0.02"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0.015 0 0"/>
			<material name="black"/>
		</visual>
	</link>

	<joint name="base_to_front_handle" type="fixed">
    	<parent link="chassis"/>
    	<child link="front_handle"/>
    	<origin xyz="0.1665 0.0 0.0365" rpy="0 0 0"/>
  	</joint>

  	<link name="rear_handle">
		<visual>
			<geometry>
				<box size="0.03 0.280 0.02"/>
			</geometry>
			<origin rpy="0 0 0" xyz="-0.015 0 0"/>
			<material name="black"/>
		</visual>
	</link>

	<joint name="base_to_rear_handle" type="fixed">
    	<parent link="chassis"/>
    	<child link="rear_handle"/>
    	<origin xyz="-0.1665 0.0 0.0365" rpy="0 0 0"/>
  	</joint> -->

	<link name="imu_link"/>

	<joint name="imu_joint" type="fixed">
		<parent link="chassis"/>
		<child link="imu_link"/>
		<origin xyz="0 0 0.006"/>
	</joint>


	<link name="base_scan">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://ares_description/meshes/lidar.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="scan_joint" type="fixed">
    <parent link="chassis"/>
    <child link="base_scan"/>
    <origin xyz="0 0 0.093" rpy="1.57075 0 0"/>
  </joint>


  	<gazebo>
		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotnamespace>/</robotnamespace>
		</plugin>
	</gazebo>

</robot>